-- Customer authentication constraints. Apply after resolving duplicate non-empty emails.
ALTER TABLE sy_account
    MODIFY EMAIL VARCHAR(255) NOT NULL,
    MODIFY PASSWORD VARCHAR(255) NOT NULL,
    MODIFY NAME VARCHAR(100) NOT NULL,
    MODIFY NICKNAME VARCHAR(100) NULL,
    MODIFY MASTER_YN VARCHAR(1) NOT NULL DEFAULT 'N',
    MODIFY INIT_YN VARCHAR(1) NOT NULL DEFAULT 'N',
    MODIFY DEL_YN VARCHAR(1) NOT NULL DEFAULT 'N',
    ADD CONSTRAINT uk_sy_account_email UNIQUE (EMAIL);
